<?php
/* This file was generated by the install process. You can edit it. Please see config.original.php to understand the configuration items. */
$cfg = array (
  'web_root' => 'http://share.awaken-game.com/',
  'var_root' => '/home/data/',
  'lang' => 'en',
  'style' => 'modern',
  'organisation' => 'BPR',
  'contactperson' => '',
  'title' => 'Awaken Puzzle Sharing Service',
  'preview' => false,
  'enable_crypt' => false,
  'link_name_length' => 8,
  'upload_password' => 
  array (
  ),
  'upload_ip' => 
  array (
  ),
  'admin_password' => '538ff90db04b5bbdc07e2e8051f9d4d65f09d0dfa228e83434450601a5600948',
  'admin_http_auth_user' => '',
  'availabilities' => 
  array (
    'minute' => true,
    'hour' => true,
    'day' => true,
    'week' => true,
    'month' => true,
    'quarter' => false,
    'year' => false,
    'none' => false,
  ),
  'availability_default' => 'month',
  'maximal_upload_size' => 1,
  'proxy_ip' => 
  array (
  ),
  'installation_done' => true,
);
